name: Bug Report
description: Report a Bug.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report and helping to improve Utlity UI!
  - type: input
    id: discord
    attributes:
      label: Discord Username
      description: If you have discord, we would appreciate it if we could contact you.
      placeholder: ex. @wumpus
    validations:
      required: false
  - type: input
    id: xbox
    attributes:
      label: Microsoft Username
      description: Please provide you Microsoft Account Name, this is your gamertag or your Minecraft Name.
      placeholder: ex. creperozelot
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: On which platform did you play Minecraft using this pack?
      options:
        - Windows
        - Mac OS
        - Linux
        - Android
        - IOS
        - Other
      default: 0
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: Os Version
      description: What is your OS Version?
      placeholder: ex. Windows 11 23H2
    validations:
      required: true
  - type: input
    id: mc_version
    attributes:
      label: Minecraft Version
      description: On which version did you play Minecraft using this pack?
      placeholder: ex. 1.21.50 Release or 1.22.40-Snapshot Beta
    validations:
      required: true
  - type: textarea
    id: bug_desc
    attributes:
      label: What happend? / What did not work?
      description: "Please tell us what wasn't working, if possible include logs or your settings."
      render: markdown
  - type: checkboxes
    id: valid
    attributes:
      label: Please check and validate all checkboxes befor your submittion.
      description: By submitting this issue ... 
      options:
        - label: I aggree that I searched for dupplicate issue reports.
          required: true
        - label: I aggree that I allow Utility Club processing my data provide in this form.
          required: true
        - label: I accept that I have filled out this form truthfully and as well as possible
          required: true
