name: Manual Release Push

permissions:
  contents: write

on:
  workflow_dispatch: # Allows triggering from the Actions UI.

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Parse Release.json
      - name: Read Release.json
        id: parse-json
        run: |
          RELEASE_DATA=$(cat Release.json)
          MCPE_VERSION=$(echo $RELEASE_DATA | jq -r '.["mcpe-version"]')
          MAJOR_VERSION=$(echo $RELEASE_DATA | jq -r '.["major-version"]')
          MINOR_VERSION=$(echo $RELEASE_DATA | jq -r '.["minor-version"]')
          CHANGELOG=$(echo $RELEASE_DATA | jq -r '.changelog')
          echo "MCPE_VERSION=$MCPE_VERSION" >> $GITHUB_ENV
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV
          echo "MINOR_VERSION=$MINOR_VERSION" >> $GITHUB_ENV
          echo "CHANGELOG=$CHANGELOG" >> $GITHUB_ENV

      # Step 3: Create pack.zip
      - name: Create pack.zip
        run: zip -r pack.zip . -x "*.git*"

      # Step 4: Create a GitHub Release
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}
          release_name: Release v${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}
          body: ${{ env.CHANGELOG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Upload the pack.zip file
      - name: Upload pack.zip
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./pack.zip
          asset_name: pack.zip
          asset_content_type: application/zip
